<h1><?= ucfirst($this->getActionName()) ?> thread</h1>

<form action="<?= $this->getActionName() ?>" method="POST">
    <label for="name">Name:</label>
    <br>
    <input typeof="text" name="name" id="name" value="<?= $this->getThreadName($data) ?>">
    <br>
    <label for="description">Description:</label>
    <br>
    <textarea maxlength="255" name="description" id="description"><?= $this->getThreadDescription($data) ?></textarea>
    <br>
    <input type="hidden" name="original_thread" value="<?= $this->getThreadName($data) ?>">
    <input type="submit">
</form>

<?php if(!$this->isNewThread()): ?>
    <a href="delete?thread=<?= $this->getThreadName($data) ?>&action=delete"><button>Delete thread</button></a>
<?php endif; ?>
