<h1><?= ucfirst($this->getActionName()) ?> topic</h1>

<form action="<?= $this->getActionName() ?>" method="POST">
    <label for="name">Name:</label>
    <br>
    <input typeof="text" name="name" id="name" value="<?= $this->getTopicName($data) ?>">
    <br>
    <label for="description">Description:</label>
    <br>
    <textarea maxlength="255" name="description" id="description"><?= $this->getTopicDescription($data) ?></textarea>
    <br>
    <lable for="thread">Thread:</lable>
    <br>
    <input type="hidden" name="thread" value="<?= \classes\ParamsHandler::get('thread') ?>">

    <?php if(!$this->isNewTopic()): ?>
        <input type="hidden" name="id" value="<?= \classes\ParamsHandler::get('topic') ?>">
    <?php endif; ?>

    <input type="submit">
</form>

<?php if(!$this->isNewTopic()): ?>
    <a href="delete?thread=<?= \classes\ParamsHandler::get('thread') ?>&topic=<?= $this->getTopicId($data) ?>"><button>Delete topic</button></a>
<?php endif; ?>