<?php foreach ($data as $thread):?>
<table class="table" border="1">
    <tr>
        <th>Thread</th>
        <th>Description</th>
        <th>Topics</th>
        <th>Posts</th>
    </tr>
        <tr>
            <td><a href="topic/index?thread=<?= $thread->getName() ?>"><b><?= $thread->getName() ?></b></a></td>
            <td><?= $thread->getDescription() ?></td>
        </tr>
    </a>
</table>
<?php endforeach; ?>