<h1>Topics for <?= $data['thread']->getName() ?></h1>
<?php if(\classes\SessionWrapper::has('id')): ?>
    <a href="/topic/edit?thread=<?= $data['thread']->getId() ?>&topic=newtopic&action=create">Create new topic</a>
<?php endif; ?>

<table class="table is-fullwidth" border="1">
    <tr>
        <th>Topic</th>
        <th>Description</th>
        <th>Poster</th>
        <th>Date</th>
        <th>Latest post</th>
    </tr>
    <?php foreach($data['topics'] as $topic): ?>
    <tr>
        <td><a href="/topic/posts?topic=<?= $topic->getTopicId() ?>"><?= $topic->getName() ?></a></td>
        <td><?= $topic->getDescription() ?></td>
        <td><?= $topic->getTopicCreator() ?></td>
        <td><?= $topic->getDateCreated() ?></td>
        <td>Post</td>
        <?php if(\classes\SessionWrapper::has('administrator') || $topic->getTopicCreator() === \classes\SessionWrapper::get('name')): ?>
            <td><a href="/topic/edit?thread=<?= $data['thread']->getId() ?>&topic=<?= $topic->getTopicId() ?>&action=update">Edit</a></td>
        <?php endif; ?>
    </tr>
    <?php endforeach; ?>
</table>